#Simulation Parameters
SIMULATION_DURATION=100
NUM_SERVERS=1

#Legitimate Network Parameters
LEGITIMATE_TRAFFIC_RATE=1
LEGITIMATE_CLIENT_COUNT=5
LEGITIMATE_LOAD_SIZE=1

#Malicious Network Parameters
MALICIOUS_TRAFFIC_RATE=2
MALICIOUS_CLIENT_COUNT=5
MALICIOUS_LOAD_SIZE=10