#TODO: Research param rules to use to best model these interactions (i.e.: Avg malicious request is 4:1 and DDoS Traffic Rate should be x:y)

#Simulation Parameters
SIMULATION_DURATION=500
NUM_SERVERS=10

#Network Server Parameters
REQUEST_TIMEOUT=10
SERVER_TIMEOUT=2
PROCESSING_POWER=200
MAX_REQUESTS_CONCURRENT=20
MAX_REQUEST_QUEUE_LENGTH=500
CPU_UTILIZATION_HEALTH_WEIGHT=0.4
QUEUE_UTILIZATION_HEALTH_WEIGHT=0.6

#Network Server Utilization Thresholds
INCREASED_UTILIZATION=.70
HIGH_UTILIZATION=.85
CRITICAL_UTILIZATION=.95

#Legitimate Network Parameters
LEGITIMATE_TRAFFIC_RATE=2
LEGITIMATE_CLIENT_COUNT=500
LEGITIMATE_LOAD_SIZE_LOWER=1
LEGITIMATE_LOAD_SIZE_UPPER=3

#Malicious Network Parameters
MALICIOUS_TRAFFIC_RATE=20
MALICIOUS_CLIENT_COUNT=100
MALICIOUS_LOAD_SIZE_LOWER=10
MALICIOUS_LOAD_SIZE_UPPER=25